# Generated by Django 3.0.3 on 2020-06-16 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=264)),
                ('rollnumber', models.IntegerField(unique=True)),
                ('batch', models.CharField(max_length=264)),
            ],
        ),
    ]
